# Generated by Django 5.2.10 on 2026-01-25 21:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("website", models.URLField(blank=True)),
                ("country", models.CharField(default="TR", max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "accounts_organization",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["slug"], name="accounts_or_slug_7a4a7c_idx"),
                    models.Index(fields=["is_active"], name="accounts_or_is_acti_483dea_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("avatar_url", models.URLField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "language",
                    models.CharField(
                        choices=[("tr", "Türkçe"), ("en", "English")], default="tr", max_length=10
                    ),
                ),
                ("timezone", models.CharField(default="Europe/Istanbul", max_length=50)),
                ("receive_notifications", models.BooleanField(default=True)),
                ("receive_emails", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts_user_profile",
            },
        ),
        migrations.CreateModel(
            name="OrganizationMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("user", "User"),
                            ("viewer", "Viewer"),
                        ],
                        default="user",
                        max_length=20,
                    ),
                ),
                ("can_create_batches", models.BooleanField(default=False)),
                ("can_download_exports", models.BooleanField(default=False)),
                ("can_manage_disputes", models.BooleanField(default=False)),
                ("can_manage_team", models.BooleanField(default=False)),
                ("invited_at", models.DateTimeField(blank=True, null=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="accounts.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="org_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts_organization_member",
                "ordering": ["-joined_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "role"], name="accounts_or_organiz_5236ad_idx"
                    )
                ],
                "unique_together": {("organization", "user")},
            },
        ),
    ]
