# Generated by Django 5.2.10 on 2026-01-25 21:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("batches", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisputeRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("email_bounce", "Email Hard Bounce"),
                            ("phone_invalid", "Phone Invalid"),
                            ("firm_inactive", "Firm Inactive/Closed"),
                            ("duplicate", "Duplicate Entry"),
                            ("no_response", "No Response"),
                            ("wrong_person", "Wrong Contact Person"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("accept", "Accept Refund"),
                            ("reject", "Reject Refund"),
                            ("manual", "Manual Review"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("priority", models.PositiveIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "disputes_dispute_rule",
                "ordering": ["-priority", "rule_type"],
            },
        ),
        migrations.CreateModel(
            name="Dispute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("reason", models.TextField(help_text="Why is the data inaccurate?")),
                ("evidence_url", models.URLField(blank=True, null=True)),
                ("evidence_data", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_review", "In Review"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("accept", "Accept Refund"),
                            ("reject", "Reject"),
                            ("manual", "Manual Review"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "decision_reason_code",
                    models.CharField(
                        blank=True,
                        help_text="Rule type that triggered decision (from DisputeRule)",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("refund_amount", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("refund_initiated_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disputes",
                        to="batches.batch",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disputes",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "db_table": "disputes_dispute",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DisputeItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("field_name", models.CharField(max_length=255)),
                (
                    "reported_value",
                    models.TextField(help_text="What the customer says the correct value is"),
                ),
                ("current_value", models.TextField(help_text="What we have in our database")),
                ("is_accepted", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="batches.batchitem",
                    ),
                ),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="disputes.dispute",
                    ),
                ),
            ],
            options={
                "db_table": "disputes_dispute_item",
            },
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(
                fields=["organization", "status"], name="disputes_di_organiz_838af8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(fields=["batch"], name="disputes_di_batch_i_aa0ccd_idx"),
        ),
    ]
