#!/bin/bash
# Anka Platform - Development Environment Setup Complete!
# =======================================================

# ✅ Local Development Environment Ready!
# Both backend and frontend services are running

echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                  🚀 ANKA PLATFORM READY!                       ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "📍 URLs:"
echo "   🏠 Frontend:      http://localhost:3000"
echo "   🔧 API:           http://localhost:8000/api"
echo "   📊 Admin:         http://localhost:8000/admin"
echo "   📖 API Docs:      http://localhost:8000/api/docs"
echo "   💚 Health Check:  http://localhost:8000/api/health/"
echo ""
echo "📋 Running Services:"
ps aux | grep -E "runserver|npm run dev" | grep -v grep | sed 's/^/   /'
echo ""
echo "📚 Documentation:"
echo "   • Local Dev:      ./dev-local.sh"
echo "   • Docker Dev:     ./dev-docker.sh"
echo "   • Setup:          ./setup.sh"
echo ""
echo "🛑 Stopping Services:"
echo "   1. Press Ctrl+C in the terminal where dev-local.sh is running"
echo "   2. Or run: pkill -f 'runserver|npm run dev'"
echo ""
echo "🔄 Restarting Services:"
echo "   1. Manual Backend:  cd services/backend && source venv/bin/activate && python manage.py runserver"
echo "   2. Manual Frontend: cd services/frontend && npm run dev"
echo ""
echo "📊 Database:"
echo "   • SQLite (local): db.sqlite3"
echo "   • PostgreSQL (Docker): Configured for docker-compose"
echo ""
echo "✨ Project Structure:"
echo "   services/backend/       Django REST API"
echo "   services/frontend/      Next.js frontend"
echo "   tests/                  Test suites"
echo "   docs/                   Documentation (ADR, API, etc)"
echo "   infra/                  Docker & Infrastructure"
echo ""
echo "Next Steps:"
echo "   1. ✅ Backend running (Django)"
echo "   2. ✅ Frontend running (Next.js)"
echo "   3. 🔄 Create models & serializers"
echo "   4. 🔄 Implement API endpoints"
echo "   5. 🔄 Build frontend pages"
echo ""
echo "Need help?"
echo "   • View Django logs:  tail -f django.log"
echo "   • View Next.js logs: tail -f nextjs.log"
echo "   • Django shell:      cd services/backend && source venv/bin/activate && python manage.py shell"
echo ""
