# Generated by Django 5.2.10 on 2026-01-25 21:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_by", models.CharField(max_length=255)),
                ("city", models.CharField(db_index=True, max_length=100)),
                ("sector", models.CharField(db_index=True, max_length=100)),
                ("filters", models.JSONField(default=dict)),
                ("sort_rule_version", models.PositiveIntegerField(default=1)),
                (
                    "query_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA256 of (city + sector + filters_json + sort_rule_version)",
                        max_length=64,
                    ),
                ),
                ("input_snapshot", models.JSONField(default=dict)),
                ("total_records", models.PositiveIntegerField(default=0)),
                ("processed_records", models.PositiveIntegerField(default=0)),
                ("error_records", models.PositiveIntegerField(default=0)),
                ("record_count_estimate", models.PositiveIntegerField(default=0)),
                ("estimated_cost", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("csv_url", models.URLField(blank=True, null=True)),
                ("xlsx_url", models.URLField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "db_table": "batches_batch",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BatchItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("firm_id", models.CharField(db_index=True, max_length=255)),
                ("firm_name", models.CharField(max_length=255)),
                ("is_verified", models.BooleanField(default=False)),
                ("has_error", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
                ("data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="batches.batch",
                    ),
                ),
            ],
            options={
                "db_table": "batches_batch_item",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="batch",
            index=models.Index(
                fields=["organization", "status"], name="batches_bat_organiz_ce2acf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="batch",
            index=models.Index(fields=["query_hash"], name="batches_bat_query_h_efcaeb_idx"),
        ),
        migrations.AddIndex(
            model_name="batch",
            index=models.Index(fields=["city", "sector"], name="batches_bat_city_ef4436_idx"),
        ),
        migrations.AddIndex(
            model_name="batchitem",
            index=models.Index(fields=["batch", "firm_id"], name="batches_bat_batch_i_1be343_idx"),
        ),
        migrations.AddIndex(
            model_name="batchitem",
            index=models.Index(fields=["is_verified"], name="batches_bat_is_veri_88a41a_idx"),
        ),
    ]
