# Generated by Django 5.2.10 on 2026-01-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='aborted_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='batch',
            name='contacts_enriched',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='batch',
            name='ids_collected',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='batch',
            name='ids_verified',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='batch',
            name='skipped_404',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('COLLECTING_IDS', 'Collecting IDs'), ('FILTERING', 'Filtering'), ('ENRICHING_CONTACTS', 'Enriching Contacts'), ('READY', 'Ready'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed'), ('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='CREATED', max_length=20),
        ),
    ]
