# Generated by Django 5.2.11 on 2026-02-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("batches", "0003_batch_emails_enriched"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("COLLECTING_IDS", "Collecting IDs"),
                    ("FILTERING", "Filtering"),
                    ("ENRICHING_CONTACTS", "Enriching Contacts"),
                    ("ENRICHING_EMAILS", "Enriching Emails"),
                    ("READY", "Ready"),
                    ("PARTIAL", "Partial"),
                    ("FAILED", "Failed"),
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="CREATED",
                max_length=20,
            ),
        ),
    ]
