# Generated by Django 5.2 on 2025-07-06 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calculationhistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Hesaplama Geçmişi', 'verbose_name_plural': 'Hesaplama Geçmişleri'},
        ),
        migrations.AddField(
            model_name='calculationhistory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='calculationhistory',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='Hata Mesajı'),
        ),
        migrations.AddField(
            model_name='calculationhistory',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi'),
        ),
        migrations.AddField(
            model_name='calculationhistory',
            name='is_successful',
            field=models.BooleanField(default=True, verbose_name='Başarılı mı?'),
        ),
        migrations.AddField(
            model_name='calculationhistory',
            name='map_coordinates',
            field=models.JSONField(blank=True, null=True, verbose_name='Harita Koordinatları'),
        ),
        migrations.AddField(
            model_name='calculationhistory',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='calculationhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme Zamanı'),
        ),
        migrations.AlterField(
            model_name='calculationhistory',
            name='calculation_type',
            field=models.CharField(choices=[('arazi_alani', 'Arazi Alanı Hesaplama'), ('dikili_alan', 'Dikili Alan Hesaplama'), ('bag_evi', 'Bağ Evi Hesaplama'), ('yapilasma', 'Yapılaşma Hesaplama'), ('mesafe', 'Mesafe Hesaplama'), ('other', 'Diğer Hesaplama')], max_length=50, verbose_name='Hesaplama Türü'),
        ),
        migrations.AlterField(
            model_name='calculationhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı'),
        ),
        migrations.AlterField(
            model_name='calculationhistory',
            name='parameters',
            field=models.JSONField(verbose_name='Parametreler'),
        ),
        migrations.AlterField(
            model_name='calculationhistory',
            name='result',
            field=models.JSONField(blank=True, null=True, verbose_name='Sonuç'),
        ),
        migrations.CreateModel(
            name='MapInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('point_mark', 'Nokta İşaretleme'), ('area_draw', 'Alan Çizme'), ('line_draw', 'Çizgi Çizme'), ('polygon_draw', 'Poligon Çizme'), ('marker_place', 'İşaretçi Yerleştirme'), ('zoom', 'Yakınlaştırma'), ('pan', 'Kaydırma')], max_length=20, verbose_name='Etkileşim Türü')),
                ('coordinates', models.JSONField(verbose_name='Koordinatlar')),
                ('zoom_level', models.IntegerField(blank=True, null=True, verbose_name='Yakınlaştırma Seviyesi')),
                ('map_layer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Harita Katmanı')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('session_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Oturum ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Harita Etkileşimi',
                'verbose_name_plural': 'Harita Etkileşimleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
