# Generated by Django 5.2 on 2025-07-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0003_alter_calculationhistory_calculation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculationhistory',
            name='calculation_type',
            field=models.CharField(choices=[('arazi_alani', 'Arazi Alanı Hesaplama'), ('dikili_alan', 'Dikili Alan Hesaplama'), ('bag_evi', 'Bağ Evi Hesaplama'), ('yapilasma', 'Yapılaşma Hesaplama'), ('mesafe', 'Mesafe Hesaplama'), ('sera', 'Sera Hesaplaması'), ('aricilik', 'Arıcılık Tesisi Hesaplaması'), ('mantar-tesisi', 'Mantar Tesisi Hesaplaması'), ('solucan-tesisi', 'Solucan Tesisi Hesaplaması'), ('buyukbas', 'Büyükbaş Hayvancılık Hesaplaması'), ('kucukbas', 'Küçükbaş Hayvancılık Hesaplaması'), ('kanatli', 'Kanatlı Hayvancılık Hesaplaması'), ('hara', 'Hara Tesisi Hesaplaması'), ('tarimsal-depo', 'Tarımsal Depo Hesaplaması'), ('lisansli-depo', 'Lisanslı Depo Hesaplaması'), ('hububat-silo', 'Hububat Silo Hesaplaması'), ('yikama-tesisi', 'Yıkama Tesisi Hesaplaması'), ('kurutma-tesisi', 'Kurutma Tesisi Hesaplaması'), ('soguk-hava-deposu', 'Soğuk Hava Deposu Hesaplaması'), ('zeytinyagi-fabrikasi', 'Zeytinyağı Fabrikası Hesaplaması'), ('su-depolama', 'Su Depolama Tesisi Hesaplaması'), ('su-kuyulari', 'Su Kuyuları Hesaplaması'), ('evcil-hayvan', 'Evcil Hayvan Bakımevi Hesaplaması'), ('sut-sigirciligi', 'Süt Sığırcılığı Hesaplaması'), ('besi-sigirciligi', 'Besi Sığırcılığı Hesaplaması'), ('agil-kucukbas', 'Ağıl (Küçükbaş) Hesaplaması'), ('kumes-yumurtaci', 'Kümes (Yumurtacı) Hesaplaması'), ('kumes-etci', 'Kümes (Etçi) Hesaplaması'), ('kumes-gezen', 'Kümes (Gezen) Hesaplaması'), ('kumes-hindi', 'Kümes (Hindi) Hesaplaması'), ('kaz-ordek', 'Kaz-Ördek Hesaplaması'), ('ipek-bocekciligi', 'İpek Böcekçiliği Hesaplaması'), ('zeytinyagi-uretim-tesisi', 'Zeytinyağı Üretim Tesisi Hesaplaması'), ('meyve-sebze-kurutma', 'Meyve-Sebze Kurutma Tesisi Hesaplaması'), ('other', 'Diğer Hesaplama')], max_length=50, verbose_name='Hesaplama Türü'),
        ),
    ]
