# Generated by Django 5.2 on 2025-08-07

from django.conf import settings
from django.db import migrations, models


def clean_duplicate_calculations(apps, schema_editor):
    """Duplicate calculation kayıtlarını temizle"""
    CalculationHistory = apps.get_model('calculations', 'CalculationHistory')
    
    # Duplicate kayıtları bul (user, calculation_type, title üçlüsü aynı olanlar)
    duplicates = []
    seen = set()
    
    for calc in CalculationHistory.objects.all().order_by('created_at'):
        key = (calc.user_id, calc.calculation_type, calc.title)
        if key in seen:
            duplicates.append(calc.id)
        else:
            seen.add(key)
    
    # Duplicate kayıtları sil (en eskilerini tut, yenileri sil)
    if duplicates:
        CalculationHistory.objects.filter(id__in=duplicates).delete()
        print(f"🧹 {len(duplicates)} duplicate calculation kaydı temizlendi")


def reverse_clean_duplicates(apps, schema_editor):
    """Reverse operation - hiçbir şey yapmıyoruz"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0005_alter_calculationhistory_calculation_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Önce calculation_type field'ını güncelleyelim 
        migrations.AlterField(
            model_name='calculationhistory',
            name='calculation_type',
            field=models.CharField(choices=[('arazi_alani', 'Arazi Alanı Hesaplama'), ('dikili_alan', 'Dikili Alan Hesaplama'), ('bag-evi', 'Bağ Evi Hesaplama'), ('yapilasma', 'Yapılaşma Hesaplama'), ('mesafe', 'Mesafe Hesaplama'), ('sera', 'Sera Hesaplaması'), ('aricilik', 'Arıcılık Tesisi Hesaplaması'), ('mantar-tesisi', 'Mantar Tesisi Hesaplaması'), ('solucan-tesisi', 'Solucan Tesisi Hesaplaması'), ('buyukbas', 'Büyükbaş Hayvancılık Hesaplaması'), ('kucukbas', 'Küçükbaş Hayvancılık Hesaplaması'), ('kanatli', 'Kanatlı Hayvancılık Hesaplaması'), ('hara', 'Hara Tesisi Hesaplaması'), ('tarimsal-depo', 'Tarımsal Depo Hesaplaması'), ('tarimsal-amacli-depo', 'Tarımsal Amaçlı Depo Hesaplaması'), ('lisansli-depo', 'Lisanslı Depo Hesaplaması'), ('hububat-silo', 'Hububat Silo Hesaplaması'), ('yikama-tesisi', 'Yıkama Tesisi Hesaplaması'), ('kurutma-tesisi', 'Kurutma Tesisi Hesaplaması'), ('soguk-hava-deposu', 'Soğuk Hava Deposu Hesaplaması'), ('zeytinyagi-fabrikasi', 'Zeytinyağı Fabrikası Hesaplaması'), ('su-depolama', 'Su Depolama Tesisi Hesaplaması'), ('su-kuyulari', 'Su Kuyuları Hesaplaması'), ('evcil-hayvan', 'Evcil Hayvan Bakımevi Hesaplaması'), ('sut-sigirciligi', 'Süt Sığırcılığı Hesaplaması'), ('besi-sigirciligi', 'Besi Sığırcılığı Hesaplaması'), ('agil-kucukbas', 'Ağıl (Küçükbaş) Hesaplaması'), ('kumes-yumurtaci', 'Kümes (Yumurtacı) Hesaplaması'), ('kumes-etci', 'Kümes (Etçi) Hesaplaması'), ('kumes-gezen', 'Kümes (Gezen) Hesaplaması'), ('kumes-hindi', 'Kümes (Hindi) Hesaplaması'), ('kaz-ordek', 'Kaz-Ördek Hesaplaması'), ('ipek-bocekciligi', 'İpek Böcekçiliği Hesaplaması'), ('zeytinyagi-uretim-tesisi', 'Zeytinyağı Üretim Tesisi Hesaplaması'), ('meyve-sebze-kurutma', 'Meyve-Sebze Kurutma Tesisi Hesaplaması'), ('other', 'Diğer Hesaplama')], max_length=50, verbose_name='Hesaplama Türü'),
        ),
        
        # Duplicate kayıtları temizle
        migrations.RunPython(clean_duplicate_calculations, reverse_clean_duplicates),
        
        # Sonra UniqueConstraint ekle
        migrations.AddConstraint(
            model_name='calculationhistory',
            constraint=models.UniqueConstraint(fields=('user', 'calculation_type', 'title'), name='unique_calculation_per_user_type_title'),
        ),
    ]
