# Generated by Django 5.2 on 2025-08-08 15:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0006_clean_duplicates_and_add_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True, verbose_name='IP Adresi')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('device_fingerprint', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cihaz Parmak İzi')),
                ('log_type', models.CharField(choices=[('calculation', 'Hesaplama'), ('limit_check', 'Limit Kontrolü'), ('limit_exceeded', 'Limit Aşımı'), ('error', 'Hata'), ('security', 'Güvenlik')], default='calculation', max_length=20, verbose_name='Log Tipi')),
                ('calculation_type', models.CharField(db_index=True, max_length=100, verbose_name='Hesaplama Türü')),
                ('calculation_data', models.JSONField(default=dict, verbose_name='Hesaplama Verisi')),
                ('result_data', models.JSONField(default=dict, verbose_name='Sonuç Verisi')),
                ('is_successful', models.BooleanField(default=True, verbose_name='Başarılı mı?')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Hata Mesajı')),
                ('limit_exceeded', models.BooleanField(default=False, verbose_name='Limit Aşıldı mı?')),
                ('current_count', models.IntegerField(blank=True, null=True, verbose_name='Mevcut Sayı')),
                ('current_limit', models.IntegerField(blank=True, null=True, verbose_name='Mevcut Limit')),
                ('location_data', models.JSONField(blank=True, default=dict, verbose_name='Lokasyon Verisi')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma Zamanı')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Hesaplama Logu',
                'verbose_name_plural': 'Hesaplama Logları',
                'db_table': 'calculation_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at', 'ip_address'], name='calculation_created_cb9f3c_idx'), models.Index(fields=['created_at', 'user'], name='calculation_created_72cf8e_idx'), models.Index(fields=['calculation_type', 'created_at'], name='calculation_calcula_7eb977_idx'), models.Index(fields=['log_type', 'created_at'], name='calculation_log_typ_3049da_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyCalculationLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='IP Adresi')),
                ('device_fingerprint', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Cihaz Parmak İzi')),
                ('calculation_count', models.IntegerField(default=0, verbose_name='Hesaplama Sayısı')),
                ('limit_exceeded', models.BooleanField(default=False, verbose_name='Limit Aşıldı mı?')),
                ('limit_exceeded_at', models.DateTimeField(blank=True, null=True, verbose_name='Limit Aşılma Zamanı')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Tarih')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Zamanı')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Günlük Hesaplama Limiti',
                'verbose_name_plural': 'Günlük Hesaplama Limitleri',
                'db_table': 'daily_calculation_limits',
                'indexes': [models.Index(fields=['date', 'ip_address'], name='daily_calcu_date_4d1ee7_idx'), models.Index(fields=['date', 'user'], name='daily_calcu_date_efa1dd_idx')],
                'unique_together': {('ip_address', 'device_fingerprint', 'date'), ('user', 'date')},
            },
        ),
    ]
