# Generated by Django 5.2 on 2026-01-01 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0009_pageview_userinteraction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinteraction',
            name='user',
        ),
        migrations.DeleteModel(
            name='PageView',
        ),
        migrations.DeleteModel(
            name='UserInteraction',
        ),
    ]
