# Generated by Django 5.2 on 2025-07-06 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Giriş Yaptı'), ('logout', 'Çıkış Yaptı'), ('calculation', 'Hesaplama Yaptı'), ('map_point', 'Harita Noktası İşaretledi'), ('profile_update', 'Profil Güncelledi'), ('password_change', 'Şifre Değiştirdi'), ('file_upload', 'Dosya Yükledi'), ('data_export', 'Veri İndirdi')], max_length=20, verbose_name='Aktivite Türü')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Adresi')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='Tarayıcı Bilgisi')),
                ('location_data', models.JSONField(blank=True, null=True, verbose_name='Konum Bilgisi')),
                ('calculation_data', models.JSONField(blank=True, null=True, verbose_name='Hesaplama Verileri')),
                ('result_data', models.JSONField(blank=True, null=True, verbose_name='Sonuç Verileri')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kullanıcı Aktivitesi',
                'verbose_name_plural': 'Kullanıcı Aktiviteleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
