# Generated by Django 5.2 on 2025-07-10 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('failed_login', 'Başarısız Giriş'), ('failed_register', 'Başarısız Kayıt'), ('rate_limit_exceeded', 'Rate Limit Aşıldı'), ('suspicious_activity', 'Şüpheli Aktivite'), ('password_change', 'Şifre Değiştirildi'), ('account_deleted', 'Hesap Silindi'), ('multiple_failed_attempts', 'Çoklu Başarısız Deneme')], max_length=30, verbose_name='Olay Türü')),
                ('severity', models.CharField(choices=[('low', 'Düşük'), ('medium', 'Orta'), ('high', 'Yüksek'), ('critical', 'Kritik')], default='medium', max_length=10, verbose_name='Önem Derecesi')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Adresi')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='Tarayıcı Bilgisi')),
                ('username_attempted', models.CharField(blank=True, max_length=150, null=True, verbose_name='Denenen Kullanıcı Adı')),
                ('email_attempted', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Denenen E-posta')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='Ek Veriler')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_events', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Güvenlik Olayı',
                'verbose_name_plural': 'Güvenlik Olayları',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='accounts_se_event_t_67c552_idx'), models.Index(fields=['ip_address', 'created_at'], name='accounts_se_ip_addr_028bd7_idx'), models.Index(fields=['severity', 'created_at'], name='accounts_se_severit_6d83fc_idx')],
            },
        ),
    ]
