# Generated by Django 5.2 on 2025-07-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_securityevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_password_reset_email',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Son Şifre Sıfırlama Maili'),
        ),
    ]
