# Generated by Django 5.2 on 2025-08-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_last_password_reset_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityevent',
            name='event_type',
            field=models.CharField(choices=[('failed_login', 'Başarısız Giriş'), ('failed_register', 'Başarısız Kayıt'), ('rate_limit_exceeded', 'Rate Limit Aşıldı'), ('suspicious_activity', 'Şüpheli Aktivite'), ('password_change', 'Şifre Değiştirildi'), ('account_deleted', 'Hesap Silindi'), ('failed_account_deletion', 'Başarısız Hesap Silme'), ('multiple_failed_attempts', 'Çoklu Başarısız Deneme')], max_length=30, verbose_name='Olay Türü'),
        ),
    ]
