# Generated by Django 5.2 on 2025-08-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_securityevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activation_mail_sent',
            field=models.BooleanField(default=False, verbose_name='Aktivasyon Maili Gönderildi'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='activation_mail_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Aktivasyon Maili Gönderim Zamanı'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='admin_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Admin Notları'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='awaiting_activation',
            field=models.BooleanField(default=False, verbose_name='Aktivasyon Bekliyor'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='awaiting_password_reset',
            field=models.BooleanField(default=False, verbose_name='Şifre Sıfırlama Bekliyor'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password_reset_mail_sent',
            field=models.BooleanField(default=False, verbose_name='Şifre Sıfırlama Maili Gönderildi'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password_reset_mail_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Şifre Sıfırlama Maili Gönderim Zamanı'),
        ),
    ]
