# Generated by Django 5.2 on 2025-08-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_mail_tracking_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password_self_chosen',
            field=models.BooleanField(default=False, verbose_name='Kullanıcı Şifresini Kendisi Belirledi'),
        ),
    ]
