# Generated by Django 5.2 on 2025-08-24 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_password_self_chosen'),
    ]

    operations = [
    ]
