# Generated by Django 5.2 on 2025-08-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20250824_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password_reset_count_today',
            field=models.PositiveIntegerField(default=0, verbose_name='Bugünkü Şifre Sıfırlama Sayısı'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password_reset_date',
            field=models.DateField(blank=True, null=True, verbose_name='Şifre Sıfırlama Tarihi'),
        ),
    ]
