# Generated by Django 5.2 on 2025-12-19 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_trackedapicall'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='analyticsevent',
            new_name='accounts_an_session_01cfcd_idx',
            old_name='accounts_an_session__b7e4df_idx',
        ),
        migrations.RenameIndex(
            model_name='analyticsevent',
            new_name='accounts_an_event_t_254767_idx',
            old_name='accounts_an_event_t_6c9a3f_idx',
        ),
        migrations.RenameIndex(
            model_name='analyticsevent',
            new_name='accounts_an_path_f07b00_idx',
            old_name='accounts_an_path_4e0c2c_idx',
        ),
        migrations.RenameIndex(
            model_name='trackedapicall',
            new_name='accounts_tr_ip_addr_43ab56_idx',
            old_name='acc_trk_ip_created_idx',
        ),
        migrations.RenameIndex(
            model_name='trackedapicall',
            new_name='accounts_tr_session_6df596_idx',
            old_name='acc_trk_session_created_idx',
        ),
        migrations.RenameIndex(
            model_name='trackedapicall',
            new_name='accounts_tr_path_9a98ca_idx',
            old_name='acc_trk_path_created_idx',
        ),
        migrations.RenameIndex(
            model_name='trackedapicall',
            new_name='accounts_tr_calcula_ac216e_idx',
            old_name='acc_trk_calc_created_idx',
        ),
    ]
