# Generated by Django 5.2.10 on 2026-01-25 21:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditPackage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("balance", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                (
                    "total_purchased",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("total_spent", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("total_refunded", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credits",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "db_table": "ledger_credit_package",
            },
        ),
        migrations.CreateModel(
            name="RecurringCharge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "frequency",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("yearly", "Yearly")], max_length=20
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("billing_date", models.IntegerField(default=1)),
                ("next_charge_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_charges",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "db_table": "ledger_recurring_charge",
            },
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("purchase", "Credit Purchase"),
                            ("spent", "Data Retrieval"),
                            ("refund", "Refund/Dispute"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="completed",
                        max_length=20,
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        choices=[
                            ("batch", "Batch"),
                            ("payment", "Payment"),
                            ("dispute", "Dispute"),
                        ],
                        default="batch",
                        max_length=20,
                    ),
                ),
                ("reference_id", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("balance_before", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("balance_after", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "db_table": "ledger_ledger_entry",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "-created_at"],
                        name="ledger_ledg_organiz_771506_idx",
                    ),
                    models.Index(
                        fields=["transaction_type"], name="ledger_ledg_transac_bba2b8_idx"
                    ),
                    models.Index(fields=["reference_id"], name="ledger_ledg_referen_a803ec_idx"),
                ],
            },
        ),
    ]
