# Generated by Django 5.2.10 on 2026-01-25 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("ledger", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="ledgerentry",
            constraint=models.UniqueConstraint(
                fields=("reference_type", "reference_id"),
                name="ledger_unique_reference",
                violation_error_message="Bu reference için zaten bir ledger kaydı mevcut.",
            ),
        ),
    ]
