# Generated by Django 5.2 on 2026-03-26 15:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(help_text='Google Play product ID (ör: kredi_5)', max_length=100, unique=True)),
                ('display_name', models.CharField(help_text='Kullanıcıya gösterilen ad', max_length=200)),
                ('credits', models.IntegerField(help_text='Bu paketle eklenen kredi sayısı')),
                ('questions_count', models.IntegerField(help_text='credits × QUESTIONS_PER_CREDIT — bilgi amaçlı gösterim için')),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'credits'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('installation_id', models.CharField(help_text='Android tarafından gönderilen installation ID', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreditBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0, help_text='Kalan kredi (her biri 50 soru)')),
                ('total_purchased', models.IntegerField(default=0, help_text='Toplam satın alınan kredi')),
                ('total_used', models.IntegerField(default=0, help_text='Toplam kullanılan kredi')),
                ('free_set_used', models.BooleanField(default=False, help_text='Ücretsiz 50 soru kullanıldı mı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='credits.device')),
            ],
        ),
        migrations.CreateModel(
            name='ChildProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Çocuk', max_length=100)),
                ('total_correct', models.IntegerField(default=0)),
                ('total_shown', models.IntegerField(default=0)),
                ('current_difficulty', models.IntegerField(default=1)),
                ('stats_json', models.JSONField(blank=True, default=dict, help_text='Tip/zorluk bazlı detaylı istatistikler')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='credits.device')),
            ],
            options={
                'unique_together': {('device', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AiQueryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('response', models.TextField(blank=True)),
                ('provider', models.CharField(default='simulate', max_length=50)),
                ('credit_cost', models.IntegerField(default=1)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('response_time_ms', models.IntegerField(default=0)),
                ('is_free', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_queries', to='credits.childprofile')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_queries', to='credits.device')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_token', models.TextField(unique=True)),
                ('product_id', models.CharField(max_length=100)),
                ('order_id', models.CharField(blank=True, default='', max_length=255)),
                ('credits_added', models.IntegerField(default=0)),
                ('verified', models.BooleanField(default=False)),
                ('consumed', models.BooleanField(default=False)),
                ('verification_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='credits.device')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('questions_json', models.JSONField(help_text='50 sorudan oluşan set')),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('credit_used', models.BooleanField(default=False, help_text='Bu set için kredi harcandı mı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_sets', to='credits.childprofile')),
            ],
            options={
                'ordering': ['-version'],
                'unique_together': {('child', 'version')},
            },
        ),
    ]
