# Generated by Django 4.2.30 on 2026-04-10 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_add_package_and_ai_query_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField(help_text="Global benzersiz soru ID'si", unique=True)),
                ('text', models.CharField(max_length=500)),
                ('answer', models.IntegerField()),
                ('question_type', models.CharField(help_text='toplama, çıkarma, çarpma, bölme, sıralama, eksik_sayı, kesir, problem, sayma, karşılaştırma, örüntü, kare', max_length=50)),
                ('difficulty', models.IntegerField(default=1)),
                ('hint', models.CharField(blank=True, max_length=500)),
                ('batch_number', models.IntegerField(db_index=True, default=0, help_text='0=ücretsiz set, 1+=kredi ile açılan set')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['batch_number', 'question_id'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='email',
            field=models.EmailField(blank=True, help_text='Kredi satın alma için gerekli e-posta adresi', max_length=254, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='UserQuestionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved', models.BooleanField(default=False)),
                ('solve_count', models.IntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_progress', to='credits.device')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='credits.question')),
            ],
            options={
                'unique_together': {('device', 'question')},
            },
        ),
    ]
