# Generated by Django 4.2.30 on 2026-04-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0002_question_device_email_userquestionprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='solved_ids',
            field=models.JSONField(blank=True, default=list, help_text="Çözülen soru global ID'leri"),
        ),
    ]
