# Generated by Django 4.2.30 on 2026-04-18 07:47

from django.db import migrations, models
import django.db.models.deletion


def assign_existing_progress_to_active_child(apps, schema_editor):
    """Mevcut progress kayıtlarını cihazın aktif çocuğuna ata."""
    UserQuestionProgress = apps.get_model('credits', 'UserQuestionProgress')
    ChildProfile = apps.get_model('credits', 'ChildProfile')

    for progress in UserQuestionProgress.objects.filter(child__isnull=True).select_related('device'):
        # Cihazın aktif çocuğunu bul
        child = ChildProfile.objects.filter(
            device=progress.device, is_active=True
        ).first() or ChildProfile.objects.filter(
            device=progress.device
        ).first()
        if child:
            progress.child = child
            progress.save(update_fields=['child'])


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0004_childprofile_education_period_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userquestionprogress',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userquestionprogress',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_progress', to='credits.childprofile'),
        ),
        migrations.RunPython(assign_existing_progress_to_active_child, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='userquestionprogress',
            unique_together={('device', 'question', 'child')},
        ),
    ]
