# Generated by Django 4.2.30 on 2026-04-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0007_renewallock'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='renewallock',
            new_name='credits_ren_expires_1d2e9b_idx',
            old_name='credits_renewallock_expires_idx',
        ),
        migrations.AddField(
            model_name='purchaserecord',
            name='last_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaserecord',
            name='purchase_state',
            field=models.IntegerField(default=-1, help_text='Google Play purchaseState: 0=purchased, 1=canceled, 2=pending, -1=unknown'),
        ),
        migrations.AlterField(
            model_name='renewallock',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
