# Generated by Django 5.2 on 2026-04-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0008_rename_credits_renewallock_expires_idx_credits_ren_expires_1d2e9b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='childprofile',
            name='locale',
            field=models.CharField(default='tr', help_text='UI ve AI içerik dili (ISO 639-1, örn: tr, en, de)', max_length=10),
        ),
    ]
