# Generated by Django 4.2.30 on 2026-05-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0009_childprofile_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='education_period',
            field=models.CharField(blank=True, db_index=True, help_text='okul_oncesi, sinif_1, sinif_2, sinif_3, sinif_4', max_length=20),
        ),
    ]
