# Generated by Django 4.2.30 on 2026-05-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0010_add_question_education_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_code',
            field=models.CharField(blank=True, help_text='Yapılandırılmış ID: {Yıl}G{Sınıf}-B{Batch}-{SıraNo} (örn: 2025G2-B1-3001)', max_length=20, null=True, unique=True),
        ),
    ]
