# Generated by Django 4.2.30 on 2026-05-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0012_remove_creditpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='childprofile',
            name='last_sync_session_id',
            field=models.CharField(blank=True, help_text="Son işlenen istatistik oturum ID'si — idempotency için", max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='creditbalance',
            name='last_refund_check_at',
            field=models.DateTimeField(blank=True, help_text='Son iade kontrolü zamanı — 24 saatte bir throttle', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.IntegerField(help_text="Global benzersiz soru ID'si (deprecated, geriye uyumluluk)", unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(help_text='toplama, çıkarma, çarpma, bölme, sıralama, eksik_sayı, kesir, problem, sayma, karşılaştırma, örüntü', max_length=50),
        ),
    ]
