#!/bin/bash
# ============================================================================
# Crontab Setup for VPS Automated Operations
# Sets up scheduled tasks for backups, monitoring, and maintenance
# ============================================================================

set -euo pipefail

echo "⏰ Setting up VPS crontab automation..."

# Backup current crontab
crontab -l > ~/crontab-backup-$(date +%Y%m%d).txt 2>/dev/null || echo "# No existing crontab" > ~/crontab-backup-$(date +%Y%m%d).txt

# Create new crontab with our tasks
cat > /tmp/vps-crontab << 'EOF'
# ============================================================================
# VPS Automated Tasks - Generated by setup-crontab.sh
# ============================================================================

# PATH environment for scripts
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

# ============================================================================
# BACKUPS
# ============================================================================

# Daily database backup with FTP upload (2 AM)
0 2 * * * /home/akn/vps/scripts/backup-volumes-ftp.sh >> /home/akn/vps/backups/backup.log 2>&1

# Weekly full system backup (Sunday 3 AM)
0 3 * * 0 /home/akn/vps/scripts/backup-volumes-ftp.sh >> /home/akn/vps/backups/backup-weekly.log 2>&1

# ============================================================================
# SSL CERTIFICATE MANAGEMENT
# ============================================================================

# Check SSL certificates daily (6 AM)
0 6 * * * docker exec vps_nginx_main nginx -t && echo "$(date): SSL config OK" >> /home/akn/vps/logs/ssl-check.log || echo "$(date): SSL config ERROR" >> /home/akn/vps/logs/ssl-check.log

# Let's Encrypt renewal check (automatic via certbot container, but log it)
0 12 * * * docker exec vps_certbot certbot certificates --quiet && echo "$(date): Certificates checked" >> /home/akn/vps/logs/ssl-check.log 2>&1

# ============================================================================
# SYSTEM MAINTENANCE
# ============================================================================

# Clean Docker system weekly (Sunday 4 AM)
0 4 * * 0 docker system prune -f >> /home/akn/vps/logs/docker-cleanup.log 2>&1

# Update Docker images monthly (1st of month, 5 AM)
0 5 1 * * cd /home/akn/vps && docker compose pull && echo "$(date): Images updated" >> /home/akn/vps/logs/updates.log 2>&1

# Restart services monthly for maintenance (1st of month, 6 AM)
0 6 1 * * cd /home/akn/vps && ./scripts/down.sh && sleep 10 && ./scripts/up.sh >> /home/akn/vps/logs/restart.log 2>&1

# ============================================================================
# MONITORING & ALERTS
# ============================================================================

# Check disk space daily (8 AM)
0 8 * * * df -h | grep -E "(^/dev/|Use%)" > /home/akn/vps/logs/diskspace-$(date +\%Y\%m\%d).log

# Check container health every 30 minutes during business hours (9 AM - 6 PM)
*/30 9-18 * * * docker ps --format "table {{.Names}}\t{{.Status}}" | grep -v "Up" >> /home/akn/vps/logs/container-issues.log || true

# Daily service status report (9 AM)
0 9 * * * cd /home/akn/vps && ./scripts/status.sh > /home/akn/vps/logs/daily-status-$(date +\%Y\%m\%d).log

# ============================================================================
# LOG MANAGEMENT
# ============================================================================

# Rotate logs monthly (1st of month, 1 AM)
0 1 1 * * find /home/akn/vps/logs -name "*.log" -mtime +30 -delete && echo "$(date): Old logs cleaned" >> /home/akn/vps/logs/maintenance.log

# Archive weekly logs (Monday 2 AM)  
0 2 * * 1 tar -czf /home/akn/vps/logs/weekly-logs-$(date +\%Y\%U).tar.gz /home/akn/vps/logs/*.log 2>/dev/null && echo "$(date): Logs archived" >> /home/akn/vps/logs/maintenance.log

EOF

# Install the crontab
crontab /tmp/vps-crontab

# Create log directories
mkdir -p /home/akn/vps/logs

# Verify installation
echo "✅ Crontab installed. Current tasks:"
crontab -l | grep -v "^#" | grep -v "^$"

echo ""
echo "📋 Summary of automated tasks:"
echo "  • Daily: Database backups (2 AM), SSL checks (6 AM), disk monitoring (8 AM)"
echo "  • Weekly: Full backup (Sunday 3 AM), Docker cleanup (Sunday 4 AM)"
echo "  • Monthly: Image updates & service restart (1st, 5-6 AM), log rotation (1st, 1 AM)"
echo "  • Business Hours: Container health checks every 30min (9 AM - 6 PM)"
echo ""
echo "📂 Log locations:"
echo "  • Backups: /home/akn/vps/backups/"
echo "  • System: /home/akn/vps/logs/"
echo ""
echo "⚙️  To modify crontab: crontab -e"
echo "📄 Backup saved to: ~/crontab-backup-$(date +%Y%m%d).txt"