"""
Django settings for webimar_api project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import json
from pathlib import Path
from decouple import config
from datetime import timedelta
import dj_database_url  # ← GEREKLİ EKLEME

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-temp-key-for-development')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)  # Development için True yapıldı

# Test çalıştırıldığında pytest/django-runner üzerinden TESTING bayrağını aç
TESTING = False
if os.environ.get('PYTEST_CURRENT_TEST') or os.environ.get('DJANGO_TESTING'):
    TESTING = True

# Geliştirme ortamında limit kontrollerini bypass etme
DEVELOPMENT_BYPASS_LIMITS = config('DEVELOPMENT_BYPASS_LIMITS', default=True, cast=bool)

def _parse_allowed_hosts(value: str | None) -> list[str]:
    if not value:
        return []

    raw = value.strip()
    # JSON list desteği: ["example.com", "localhost"]
    if raw.startswith('['):
        try:
            parsed = json.loads(raw)
            if isinstance(parsed, list):
                return [str(item).strip() for item in parsed if str(item).strip()]
        except Exception:
            pass

    # CSV desteği: "localhost,127.0.0.1,example.com"
    return [part.strip() for part in raw.split(',') if part.strip()]


# Django 5.2: ALLOWED_HOSTS mutlaka list/tuple olmalı.
# Not: RFC-uyumsuz internal host header'lar (örn: api_backend) için
# `InternalHostMiddleware` Host header'ı normalize eder.
_DEFAULT_ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '0.0.0.0',
    '192.168.1.6',
    'tarlada-ruhsat.com.tr',
    'tarimimar.com.tr',
    'www.tarlada-ruhsat.com.tr',
    'www.tarimimar.com.tr',
    '123.45.67.89',
    '89.252.152.222',
    'webimar-api',
    'webimar-nginx',
]

ALLOWED_HOSTS = _parse_allowed_hosts(config('ALLOWED_HOSTS', default=','.join(_DEFAULT_ALLOWED_HOSTS)))

# Internal servis adları ile çalışmayı garanti et (güvenli, dışarı açılmıyor).
for _required_host in ('webimar-api', 'localhost', '127.0.0.1'):
    if _required_host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(_required_host)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party packages
    'rest_framework',
    'corsheaders',
    
    # Local apps
    'accounts',
    'calculations',
    'maps',
    'reports',
    'kullanicilar',
]

MIDDLEWARE = [
    'webimar_api.middleware.InternalHostMiddleware',  # Internal host cleanup (en üstte)
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'accounts.request_tracking_middleware.ApiRequestTrackingMiddleware',
    'accounts.middleware.SecurityLoggingMiddleware',
    'calculations.middleware.CalculationLimitMiddleware',  # Hesaplama limit kontrolü
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# API tracking (anonim dahil) - prod'da "her şeyi kaydetme" için
TRACKING_ENABLED = config('TRACKING_ENABLED', default=True, cast=bool)
TRACKING_LOG_RESPONSE_BODY = config('TRACKING_LOG_RESPONSE_BODY', default=True, cast=bool)
TRACKING_MAX_BODY_BYTES = config('TRACKING_MAX_BODY_BYTES', default=65536, cast=int)

ROOT_URLCONF = 'webimar_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Admin override için templates klasörü eklendi
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'webimar_api.wsgi.application'

# DATABASES - Ortama göre otomatik seçim
DATABASE_URL = config('DATABASE_URL', default=None)
if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL)
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'tr-tr'
TIME_ZONE = 'Europe/Istanbul'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'

# Development için
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Production için (collect static yapıldığında)
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Static files finder - Django'nun kendi admin static dosyalarını da bulabilmesi için
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# WhiteNoise ayarları - Production'da statik dosyaları serve eder
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
WHITENOISE_USE_FINDERS = True
WHITENOISE_AUTOREFRESH = True  # Development için

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework Configuration
throttle_rates_config = {
    # Test ortamında yüksek limitler kullan
    'register': '1000/min' if TESTING else '5/min',
    'password_reset': '1000/min' if TESTING else '5/min',  
    'email_verification': '1000/min' if TESTING else '10/min',
    'anon': '10000/hour' if TESTING else '100/hour',
    'user': '10000/hour' if TESTING else '1000/hour'
} if not TESTING else {}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
       # 'rest_framework.authentication.SessionAuthentication',
       # 'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # Development için, production'da değişecek
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'EXCEPTION_HANDLER': 'webimar_api.exceptions.custom_exception_handler',
}

# Test ortamında throttle rates'i tamamen kaldır
if not TESTING:
    REST_FRAMEWORK['DEFAULT_THROTTLE_RATES'] = throttle_rates_config

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# CORS ayarları (React frontend için)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:3001",        # React SPA port 3001
    "http://127.0.0.1:3001",
    "http://localhost:3003",
    "http://127.0.0.1:3003",
    "http://192.168.1.6:3000",      # Local network IP for dev
    "http://192.168.1.6:3001",      # Local network IP for React SPA
    "http://89.252.152.222:3000",  # <--- SUNUCUDAKİ REACT ADRESİNİ EKLE
    "https://tarlada-ruhsat.com.tr",  # <-- Bu satırı ekle!
    "https://tarimimar.com.tr",
    "http://tarlada-ruhsat.com.tr",   # (Varsa http ile de ekle)
    "http://tarimimar.com.tr",
]

# Development ortamında local network IP'leri için regex pattern
if DEBUG:
    CORS_ALLOWED_ORIGIN_REGEXES = [
        r"^http://192\.168\.\d+\.\d+:300[01]$",  # 192.168.x.x:3000 or 3001 pattern
        r"^http://10\.\d+\.\d+\.\d+:300[01]$",   # 10.x.x.x:3000 or 3001 pattern  
        r"^http://172\.(1[6-9]|2[0-9]|3[01])\.\d+\.\d+:300[01]$",  # 172.16-31.x.x:3000 or 3001 pattern
    ]

CORS_ALLOW_CREDENTIALS = True

# CORS metodları - DELETE dahil tüm metodlara izin ver
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# CORS headers - Authorization header dahil
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-webimar-session-id',  # Custom session header
]

# Cache settings - GSC Performance Optimization (Response time: 629ms → <200ms target)
# Development mode: Use local memory cache instead of Redis
if DEBUG:  # Development mode - no Redis dependency
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-webimar-cache',
            'TIMEOUT': 300,
            'OPTIONS': {
                'MAX_ENTRIES': 1000,
                'CULL_FREQUENCY': 3,
            }
        },
        'fallback': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-webimar-cache-fallback',
            'TIMEOUT': 300,
            'OPTIONS': {
                'MAX_ENTRIES': 500,
                'CULL_FREQUENCY': 3,
            }
        }
    }
else:  # Production mode - Redis cache
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': config('REDIS_URL', default=config('CACHE_URL', default='redis://127.0.0.1:6379/1')),
            'TIMEOUT': 300,  # 5 minutes default
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'CONNECTION_POOL_KWARGS': {
                    'max_connections': 50,
                    'retry_on_timeout': True,
                },
                'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
                'SERIALIZER': 'django_redis.serializers.json.JSONSerializer',
            },
            'KEY_PREFIX': 'webimar',
        },
        # Fallback to local memory if Redis is unavailable
        'fallback': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-webimar-cache',
            'TIMEOUT': 300,
            'OPTIONS': {
                'MAX_ENTRIES': 1000,
                'CULL_FREQUENCY': 3,
            }
        }
    }

# Cache timeout constants for different types of data
CACHE_TIMEOUT_CALCULATION = 86400  # 24 hours - Calculation results
CACHE_TIMEOUT_CONFIG = 604800      # 7 days - Configuration data
CACHE_TIMEOUT_STRUCTURE_TYPES = 3600  # 1 hour - Structure types
CACHE_TIMEOUT_ARAZI_TIPLERI = 86400   # 24 hours - Land types

# Session settings
SESSION_COOKIE_AGE = 86400  # 24 saat
SESSION_COOKIE_SECURE = not DEBUG  # Production'da True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'

# Security settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

if not DEBUG:
    # Production security settings
    # SECURE_SSL_REDIRECT False because Nginx handles SSL termination
    SECURE_SSL_REDIRECT = False
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {name} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '[{levelname}] {message}',
            'style': '{',
        },
    },
    'handlers': {
        'null': {
            'class': 'logging.NullHandler',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'maxBytes': 10485760,  # 10 MB
            'backupCount': 3,
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django.security.DisallowedHost': {
            'handlers': ['null'],
            'propagate': False,
        },
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'accounts': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        # GSC Performance: Slow query detection for response time optimization
        'django.db.backends': {
            'handlers': ['file', 'console'] if DEBUG else ['file'],
            'level': 'DEBUG' if DEBUG else 'WARNING',  # Only log slow queries in production
            'propagate': False,
        },
        'django.db.backends.schema': {
            'handlers': ['file'],
            'level': 'WARNING',  # Reduce schema noise
            'propagate': False,
        },
    },
}

# Query performance monitoring (GSC response time optimization)
if not DEBUG:  # Production only
    LOGGING['loggers']['django.db.backends']['filters'] = ['slow_queries']
    LOGGING['filters'] = {
        'slow_queries': {
            '()': 'django.utils.log.CallbackFilter',
            'callback': lambda record: 'took' in record.getMessage() and float(record.getMessage().split('took ')[1].split('s')[0]) > 0.1
        }
    }

# Create logs directory if it doesn't exist
logs_dir = BASE_DIR / 'logs'
if not os.path.exists(logs_dir):
    os.makedirs(logs_dir)

# EMAIL CONFIGURATION - Amazon SES SMTP
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='email-smtp.eu-central-1.amazonaws.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)
EMAIL_TIMEOUT = config('EMAIL_TIMEOUT', default=30, cast=int)

# AWS SES SMTP Authentication
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')

# Default sender email
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='info@tarimimar.com.tr')
SERVER_EMAIL = config('SERVER_EMAIL', default=DEFAULT_FROM_EMAIL)

# Email subject prefix
EMAIL_SUBJECT_PREFIX = config('EMAIL_SUBJECT_PREFIX', default='[Webimar] ')

# Admin bildirim e-postası (kritik kullanıcı işlemleri buraya gider)
ADMIN_NOTIFICATION_EMAIL = config('ADMIN_NOTIFICATION_EMAIL', default=DEFAULT_FROM_EMAIL or 'info@tarimimar.com.tr')

# Console backend için development ortamında
if DEBUG and EMAIL_BACKEND == 'django.core.mail.backends.console.EmailBackend':
    print("📧 Mail gönderimi konsola yönlendirildi (Development mode)")

# Email doğrulama ayarları
REQUIRE_EMAIL_VERIFICATION = config('REQUIRE_EMAIL_VERIFICATION', default=not DEBUG, cast=bool)

# Google OAuth ayarları
GOOGLE_OAUTH_CLIENT_ID = config('GOOGLE_OAUTH_CLIENT_ID', default='31411941616-59bpapcrm7t0ettkhbb0564am8mnjk91.apps.googleusercontent.com')
GOOGLE_OAUTH_CLIENT_SECRET = config('GOOGLE_OAUTH_CLIENT_SECRET', default='')  # .env dosyasından alınacak
# PROD için backend callback (deploy.yml ile bire bir aynı olmalı)
GOOGLE_OAUTH_REDIRECT_URI = config('GOOGLE_OAUTH_REDIRECT_URI', default='https://tarimimar.com.tr/api/accounts/google/callback/')

# Frontend base URL - Google OAuth sonrası yönlendirme için
FRONTEND_BASE_URL = config('FRONTEND_BASE_URL', default='https://tarimimar.com.tr' if not DEBUG else 'http://localhost:3000')

# Telegram Bot Settings
TELEGRAM_BOT_TOKEN = config('TELEGRAM_BOT_TOKEN', default='')
TELEGRAM_CHAT_ID = config('TELEGRAM_CHAT_ID', default='')

# Geliştirme ortamında da backend callback kullan (Google Console'da yetkili olmalı)
if DEBUG:
    # Dinamik portlar yerine Django API callback'ini kullanıyoruz
    # .env'den alabilir, yoksa default 8000
    GOOGLE_OAUTH_REDIRECT_URI = config('GOOGLE_OAUTH_REDIRECT_URI', default='http://localhost:8000/api/accounts/google/callback/')
if DEBUG and not REQUIRE_EMAIL_VERIFICATION:
    print("📧 Email doğrulaması devre dışı (Development mode)")
