# Generated by Django 5.2.10 on 2026-01-25 21:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("batches", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("firm_id", models.CharField(db_index=True, max_length=255, unique=True)),
                ("firm_name", models.CharField(max_length=255)),
                ("data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="batches.batch",
                    ),
                ),
            ],
            options={
                "db_table": "records_record",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="RecordField",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("field_name", models.CharField(max_length=255)),
                ("value", models.TextField()),
                ("verified", models.BooleanField(default=False)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("direct", "Direct"),
                            ("aggregated", "Aggregated"),
                            ("inferred", "Inferred"),
                            ("user_provided", "User Provided"),
                        ],
                        default="direct",
                        max_length=50,
                    ),
                ),
                ("confidence", models.FloatField(default=1.0)),
                ("source_provider", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("observed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="records.record",
                    ),
                ),
            ],
            options={
                "db_table": "records_record_field",
                "ordering": ["-observed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="record",
            index=models.Index(fields=["firm_id"], name="records_rec_firm_id_4d2bd8_idx"),
        ),
        migrations.AddIndex(
            model_name="recordfield",
            index=models.Index(
                fields=["record", "field_name"], name="records_rec_record__4befe1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recordfield",
            index=models.Index(fields=["verified"], name="records_rec_verifie_cb7e9d_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="recordfield",
            unique_together={("record", "field_name")},
        ),
    ]
