# Generated by Django 5.2.10 on 2026-02-01 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("records", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("place_id", models.CharField(max_length=200, unique=True)),
                ("name", models.CharField(max_length=300)),
                ("formatted_address", models.TextField(blank=True, null=True)),
                (
                    "latitude",
                    models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "longitude",
                    models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
                ),
                ("place_types", models.JSONField(default=list)),
                ("business_status", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "rating",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
                ),
                ("user_ratings_total", models.IntegerField(blank=True, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("phone_number", models.CharField(blank=True, max_length=50, null=True)),
                ("international_phone", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Verification"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                            ("enriched", "Enriched"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("verification_reason", models.CharField(blank=True, max_length=100, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("collected_at_stage", models.CharField(default="stage1", max_length=10)),
                ("last_enriched_stage", models.CharField(default="stage1", max_length=10)),
                ("google_search_enhanced", models.BooleanField(default=False)),
                ("enhanced_website", models.URLField(blank=True, null=True)),
                ("enhanced_phone", models.CharField(blank=True, max_length=50, null=True)),
                ("enhanced_email", models.EmailField(blank=True, max_length=254, null=True)),
                ("social_media_links", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "business_candidates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EnrichmentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "enrichment_type",
                    models.CharField(
                        choices=[
                            ("google_search", "Google Search"),
                            ("social_media", "Social Media Scraping"),
                            ("website_analysis", "Website Analysis"),
                            ("phone_verification", "Phone Number Verification"),
                        ],
                        max_length=30,
                    ),
                ),
                ("source_api", models.CharField(max_length=100)),
                ("api_calls_used", models.IntegerField(default=1)),
                ("cost_estimate", models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ("success", models.BooleanField(default=False)),
                ("data_found", models.JSONField(default=dict)),
                (
                    "confidence_score",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrichment_logs",
                        to="records.businesscandidate",
                    ),
                ),
            ],
            options={
                "db_table": "enrichment_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SearchQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_by", models.CharField(max_length=255)),
                ("query_text", models.CharField(max_length=500)),
                ("city", models.CharField(max_length=100)),
                ("sector", models.CharField(max_length=100)),
                ("location_bias", models.JSONField(blank=True, null=True)),
                (
                    "max_stage",
                    models.CharField(
                        choices=[
                            ("stage1", "Stage 1 - ID Collection"),
                            ("stage2", "Stage 2 - Verification"),
                            ("stage3", "Stage 3 - Enrichment"),
                        ],
                        default="stage1",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_candidates_found", models.IntegerField(default=0)),
                ("api_calls_made", models.JSONField(default=dict)),
                ("cost_estimate", models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("raw_results_file", models.CharField(blank=True, max_length=500, null=True)),
                ("processed_results_file", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.organization"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "search_queries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="businesscandidate",
            name="search_query",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidates",
                to="records.searchquery",
            ),
        ),
        migrations.AddIndex(
            model_name="businesscandidate",
            index=models.Index(fields=["place_id"], name="business_ca_place_i_02d601_idx"),
        ),
        migrations.AddIndex(
            model_name="businesscandidate",
            index=models.Index(
                fields=["search_query", "verification_status"],
                name="business_ca_search__614f74_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="businesscandidate",
            index=models.Index(
                fields=["verification_status"], name="business_ca_verific_8dbf0c_idx"
            ),
        ),
    ]
